name: Prod
concurrency: prod_environment
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - name: 'Checkout sources'
      uses: actions/checkout@v3
    - name: 'Setup NodeJS'
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: 'Install dependencies'
      run: yarn install
    - name: 'Run unit-tests'
      run: yarn test
    - run: yarn run lint
    - run: yarn dist
    - run: yarn run coverage
    - run: bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_SECRET_TOKEN }}
    - name: Commit GitHub Action distribution
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/index.js
        git commit -m "Build by GitHub Actions" || true
      if: job.status == 'success'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: true
      if: job.status == 'success'
