name: Release
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v3
      - name: 'Setup NodeJS'
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: 'Install dependencies'
        run: yarn install
      - name: 'Run unit-tests'
        run: yarn test
      - name: 'Semantic Release'
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'GitHub release'
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.semantic.outputs.new_release_version }}
